---
deployment:
  tasks:
    # 1. Go to the repo directory
    - export APP_DIR=/home/act/repo/RecruitIQ
    - cd $APP_DIR || exit 0

    # 2. Write a simple marker file so we know deploy ran
    - echo "Deployed at $(date)" >> deploy-test.log || true
