---
deployment:
  tasks:
    # 1. Go to the app directory
    - export APP_DIR=/home/act/repo/RecruitIQ
    - cd $APP_DIR

    # 2. Take app offline (ignore if already down)
    - php artisan down || true

    # 3. Optimise caches (safe for every deployment)
    - php artisan optimize || true

    # 4. Bring the application back up
    - php artisan up || true

    # OPTIONAL: Enable later when you are ready
    # - php artisan migrate --force || true
